### PR TITLE
Unzip everything for searchability reasons

### PR DESCRIPTION
**Pull request by majick**
The original zip files are left in place, but their contents have been exrtracted in order to improve the ability to search for them.

Most notably:
 * 01/LIBRARY.ALL contains a ton of useful discussion text
 * 08/ROMS.TXT contains a ton of useful discussion text
 * The various DOS programs had descriptive documentation

### CODE REVIEW

**Comment by majick** [comment]
I doubt this will be controversial but I didn't want to just merge it right in.  There are a handful of ZIP archives in here and they're not that searchable with lowest common denominator tools.  A couple of them contain interesting text that might be useful to search.

The on-list mention of using GitHub's search facility prodded me to consider archive file contents.

**Comment by majick** [comment]
Fixes #2

**Comment by bkw777** [comment]
This is just the result of just unzipping zip files where they were?

**Comment by majick** [comment]
Correct.  The zip files remain in place, with no deduplication or modification.  Their contents are simply left sitting out, visible  in the repo or on the filesystem.

It wound up being a couple of DOS utilities with one executable binary and one text tile, much like the handful already sitting out; there were also a couple of archives containing single text files.  In all cases, just `unzip`ped and committed.

**Comment by bkw777** [comment]
I see no problem

**Pull request merged**
